/**
 * anctions 的动作名称
 * Created by gaoju on 2018/8/16.
 */
export const ACTIONS = {
    STOP_PLAY_MEDIA: 'STOP_PLAY_MEDIA',//停止播放
    START_PLAY_MEDIA: 'START_PLAY_MEDIA',//开始播放
    LOADING_MEDIA_SUCCESS: 'LOADING_MEDIA_SUCCESS',//缓冲成功
    TO_PREVIOUS_ONE: 'TO_PREVIOUS_ONE',//上一首
    TO_NEXT_ONE: 'TO_NEXT_ONE',//下一首
    CHANGE_MUSIC_CONTROL_MODAL_VISIBILITY: 'CHANGE_MUSIC_CONTROL_MODAL_VISIBILITY'
};